### Problem 2 - Even Fibonacci Numbers
###---------------------------------------------------------------------------------------------------------------------------------------------
### Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
### 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
### By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

### Solution

current_num = 1
prev_num = 1
total = 0

while current_num <= 4000000:
	
	current_num = current_num + prev_num
	prev_num = current_num - prev_num

	if current_num % 2 == 0:
		total += current_num

print(total)